### ISSUE TITLE
[Possible Task mismatch] There is possible mismatch between week4/Task5 description and the given hint

### ISSUE THREAD

**Issue by NoHomey** [stoimenoff/up16-17#2]
В условието на [Зад5](https://github.com/stoimenoff/up16-17/tree/11a5915e1116f7f707293546913e4b34edd4123a/week4/practicum/tasks#Зад5) от week4 е казано, че трябва да се генерира произволно число в интервала [0, 100], а в указанието е показано, как се генерира произволно число в интервала [1, 10]. Предполагам, че това е по-скоро грешка от колкото подтикване да се потърси формулата за генериране на произволно число в даден целочислен интервал ...

**Comment by stoimenoff** [comment]
Точно го видях и го оправям, мерси. Не мисля, че е умишлено. Малко разснения за това как работи кода също не изглеждат излишни и мисля да ги добавя.
